### ISSUE TITLE
Something wrong with armor coexistence

### ISSUE THREAD

**Issue by bell07** [GreenXenith/halloween#1]
1. Get "Steel chestplate" and "Devil Female" costume from creative
2. Apply the costume
3. => Applying Chestplate does not work

4. Remove costume and apply chestplate
5. Applying costume does work

Expected is both work together in both directions

**Comment by GreenXenith** [comment]
This is the desired behavior. The costume is a full suit, like the hazmat suit, for instance. Armor shouldn't be able to over them.
Do note, after the 2.0 fix, masks and hoodies are now helmets/chestplates instead of suits so they can be combined with other armor. This update also improved the suit function, in case you were able to mix things other than chestplates with costumes.

Also, sorry for the late reply. I don't get notified when issues open, I need to fix that.
